# OBJECT ORIENTED PROGRAMMING

# COMMON TOPIC IN ALLMOST ALL POPULAR PROHRAMMING LANGUAGES(  PYTHON C++ JAVA)

# WITH COMMON IDEA BUT DIFFERENT SYNTAX 

# OPP IS STYLE WAY TO Warning A PROGRAM 

# VERY HELPFUL CREATING IN REAL LIFE POGRAM 

# WE WILL SEE OTHER ADAVANTAGES WHEN WE WILL SATART LEARING OPP
# @class object(instense), method 
#list class
#list object

l=[1,2,3,4]
i2=[7,8,9,1]
l3=['anas']
l.append(4)